version: '3.8'

services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: app_frontend

  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx_reverse_proxy
    depends_on:
      - app
