version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pw
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: ./todo-backend/dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 3001:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: app_backend

  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    ports:
      - 3000:3000
    container_name: app_frontend

  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx_reverse_proxy
    depends_on:
      - app
      - server
      - mongo
      - redis
