version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pw
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

  server:
    image: todo-backend
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - REDIS_URL: redis://redis:6379
      - MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    command: ['npm', 'run', 'dev']
    container_name: todo-backend-server


volumes:
  mongo_data:
  redis_data:
